[[redirects]]
  from = "http://*"
  to = "https://:splat"
  status = 301
  force = true

[[redirects]]
  from = "https://www.varnikfinance.com/*"
  to = "https://varnikfinance.com/:splat"
  status = 301
  force = true
